### ISSUE TITLE
Downloading Node Executables on Windows broken

### ISSUE THREAD

**Issue by omilke** [sdorra/buildfrontend-maven-plugin#1]
I'm on Windows 10 (x64) and this awesome plugins tries to download:

http://nodejs.org/dist/v6.10.3/x64/node.exe

Consequently, the plugin downloads a 404 error page, that, unfortunately, is not executable ;-)

Proper path seems to be:

https://nodejs.org/dist/v6.10.3/win-x64/node.exe

In the meantime, to fix builds suffering from this issue:

* download the proper executable as linked above
* replace the executable local .m2 repository with the one just downloaded
    * %USERPROFILE%\.m2\repository\com\github\sdorra\buildfrontend-node\v6.10.3\buildfrontend-node-v6.10.3-windows_x64.exe
* re-run mvn 
* enjoy

**Comment by sdorra** [comment]
fixed with version 1.2.1
